### ISSUE TITLE
Need to rename

### ISSUE THREAD

**Issue by gaborcsardi** [gaborcsardi/processx#16]
There is a bioc package called PROcess. :(

**Comment by gaborcsardi** [comment]
It is called `processx` now.

**Comment by richfitz** [comment]
So glad to see I'm not the only one who has this problem...

**Comment by gaborcsardi** [comment]
Yeah, I usually check cran when naming a package, but not bioc....

**Comment by richfitz** [comment]
Possibly devtools (or mason or whatever) could have a "check name free" function, but I'm not volunteering

**Comment by gaborcsardi** [comment]
:)
